USE master
GO

DROP DATABASE IF EXISTS Nhom6_IT17322_QuanLyCuaHangDienThoai
GO

USE master
GO

CREATE DATABASE Nhom6_IT17322_QuanLyCuaHangDienThoai
GO
USE Nhom6_IT17322_QuanLyCuaHangDienThoai
GO
-- TaiKhoan 1
CREATE TABLE TaiKhoan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
HoTen NVARCHAR(50) DEFAULT NULL,
GioiTinh Int DEFAULT 0,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Email VARCHAR(100) NOT NULL,
Sdt VARCHAR(15) DEFAULT NULL,
MatKhau VARCHAR(100) NOT NULL,
ChucVu Int DEFAULT 0,
HinhAnh Varchar(50),
TrangThai Int DEFAULT 1,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL
)
GO
-- KhachHang 2
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
GioiTinh Int DEFAULT 0,
Sdt VARCHAR(15) NOT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
CapDo int DEFAULT 0,
NgayTutHang Date DEFAULT GETDATE(),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--HoaDon 3
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdTK UNIQUEIDENTIFIER,
Ma VARCHAR(20) UNIQUE NOT NULL,
NgayTao Date DEFAULT GETDATE(),
NgayThanhToan Date DEFAULT NULL,
NgayNhanHang Date DEFAULT NULL,
NgayShip Date DEFAULT NULL,
NgayNhanMongMuon Date DEFAULT NULL,
TienShip Decimal(20, 0) DEFAULT 0,
TienMat Decimal(20, 0) DEFAULT 0,
ChuyenKhoan Decimal(20, 0) DEFAULT 0,
TenKH NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
TongTien Decimal(20, 0) DEFAULT 0,
TrangThai Int DEFAULT 1,
SdtNguoiShip VARCHAR(15) DEFAULT NULL,
TenNguoiShip NVARCHAR(50)NULL,
LoaiThanhToan Int DEFAULT 0,
GiamGia Decimal(20, 0) DEFAULT 0,
LyDo NVARCHAR(100),
lastModifiedDate Date DEFAULT NULL
)
GO
-- SanPham 4
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- CPU 5
CREATE TABLE CPU(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- MauSac 6
CREATE TABLE MauSac(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- Ram 7
CREATE TABLE Ram(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--Rom 8
CREATE TABLE Rom(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
--ManHinh 9
CREATE TABLE ManHinh(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO 
--Rom 10
CREATE TABLE Pin(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--KhuyenMai 11
CREATE TABLE KhuyenMai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
NgayBD Datetime NOT NULL,
NgayKT Datetime NOT NULL,
GiaTri int DEFAULT 0,
TrangThai int DEFAULT 0,
LoaiKM Int DEFAULT 0,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL
)

-- ChiTietSP 12
CREATE TABLE ChiTietSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdRom UNIQUEIDENTIFIER,
IdRam UNIQUEIDENTIFIER,
IdMauSac UNIQUEIDENTIFIER,
IdCPU UNIQUEIDENTIFIER,
IdManHinh UNIQUEIDENTIFIER,
IdPin UNIQUEIDENTIFIER,
LoaiHang Int DEFAULT 0,
Gia DECIMAL(20,0) DEFAULT 0,
SoLuong int DEFAULT 0,
HinhAnh Varchar(100) DEFAULT NULL,
Mota Varchar(50),
IdKhuyenMai UNIQUEIDENTIFIER,
IdSP UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)

GO
-- HoaDonChiTiet 13
CREATE TABLE HoaDonChiTiet(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
TenSP NVARCHAR(100) NOT NULL,
DonGia DECIMAL(20,0) DEFAULT 0,
Thanhtien DECIMAL(20,0) DEFAULT 0,
SoLuong INT NOT NULL,
TrangThai Int DEFAULT 1,
KhuyenMai DECIMAL(20,0) DEFAULT 0,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL,
)
GO
-- Imel 14
CREATE TABLE Imel(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdChiTietSP UNIQUEIDENTIFIER DEFAULT NULL,
Ma Char(15) UNIQUE NOT NULL,
TrangThai Int DEFAULT 1,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL
)
GO
--BaoHanh 15
CREATE TABLE BaoHanh(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
TrangThai Int DEFAULT 1,
IdImel UNIQUEIDENTIFIER,
NgayBaoHanh Date NOT NULL,
NgayHoanThanh Date DEFAULT NULL,
NgayKhachLay Date DEFAULT NULL,
LyDo NVARCHAR(100),
MoTa NVARCHAR(100),
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL
)
-- ImelBan 16
CREATE TABLE ImelBan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDonChiTiet UNIQUEIDENTIFIER,
Ma Char(15) NOT NULL,
LyDo NVARCHAR(100) NULL,
TrangThai Int DEFAULT 1,
CreatedDate Date DEFAULT GETDATE(),
lastModifiedDate Date DEFAULT NULL
)
GO
--TẠO QUAN HỆ GIỮA CÁC BẢNG
-- HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
-- HoaDon - TaiKhoan
ALTER TABLE HoaDon ADD FOREIGN KEY (IdTK) REFERENCES TaiKhoan(Id)
-- ChiTietSP - SanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSP) REFERENCES SanPham(Id)
-- ChiTietSP - ROM
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdRom) REFERENCES Rom(Id)
-- ChiTietSP - RAM
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdRam) REFERENCES Ram(Id)
-- ChiTietSP - CPU
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdCPU) REFERENCES CPU(Id)
-- ChiTietSP - MauSac
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdMauSac) REFERENCES MauSac(Id)
-- ChiTietSP - ManHinh
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdManHinh) REFERENCES ManHinh(Id)
-- ChiTietSP - Pin
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdPin) REFERENCES Pin(Id)
-- ChiTietSP - KhuyenMai
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdKhuyenMai) REFERENCES KhuyenMai(Id)
-- HoaDonChiTiet - HoaDon
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id)
-- HoaDonChiTiet - ChiTietSP
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id)
-- Imel - ChiTietSP
ALTER TABLE Imel ADD FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id)
-- BaoHanh - Imel
ALTER TABLE BaoHanh ADD FOREIGN KEY(IdImel) REFERENCES Imel(Id)
-- ImelBan - IdHoaDonChiTiet
ALTER TABLE ImelBan ADD FOREIGN KEY(IDHoaDonChiTiet) REFERENCES HoaDonChiTiet(Id)
GO

INSERT INTO TaiKhoan(Ma,HoTen,ChucVu, Email, MatKhau, HinhAnh) values ('NV001','Admin',0, 'admin', '21232F297A57A5A743894A0E4A801FC3', 'NV001'),
('NV002','NhanVien',1, 'nhanvien', '2A2FA4FE2FA737F129EF2D127B861B7E', 'NV002')
GO
INSERT INTO KhachHang(Ma, HoTen, Sdt) VALUES('MacDinh',N'Khách lẻ','0123456789')

