USE master
GO

DROP DATABASE IF EXISTS Nhom6_IT17322_QuanLyCuaHangDienThoai
GO

USE master
GO

CREATE DATABASE Nhom6_IT17322_QuanLyCuaHangDienThoai
GO
USE Nhom6_IT17322_QuanLyCuaHangDienThoai
GO
--ChucVu
CREATE TABLE ChucVu(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(50) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--TrangThaiTaiKhoan
CREATE TABLE TrangThaiTaiKhoan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- TaiKhoan
CREATE TABLE TaiKhoan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
HoTen NVARCHAR(50) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Email VARCHAR(100) NOT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
MatKhau VARCHAR(100) NOT NULL,
IdCV UNIQUEIDENTIFIER,
IdTrangThaiTK UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL
)
GO
-- KhachHang
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
Sdt VARCHAR(30) NOT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--TrangThaiHoaDon
CREATE TABLE TrangThaiHoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--HoaDon
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdTK UNIQUEIDENTIFIER,
Ma VARCHAR(20) UNIQUE NOT NULL,
IdTrangThaiHD UNIQUEIDENTIFIER,
LoaiThanhToan bit NOT NULL,
TongTien Decimal(20, 0) DEFAULT 0,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL
)
GO
-- Hang
CREATE TABLE Hang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- HDH
CREATE TABLE HDH(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
-- SanPham
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
IdHang UNIQUEIDENTIFIER,
IdHDH UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- CPU
CREATE TABLE CPU(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- MauSac
CREATE TABLE MauSac(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- DongSP
CREATE TABLE Ram(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--Rom
CREATE TABLE Rom(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--LoaiKM
CREATE TABLE LoaiKM(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--KhuyenMai
CREATE TABLE KhuyenMai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE NOT NULL,
Ten NVARCHAR(30) NOT NULL,
NgayBD Date NOT NULL,
NgayKT Date NOT NULL,
GiaTri int DEFAULT 0,
TrangThai bit DEFAULT 0,
IdLoaiKM UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)

-- ChiTietSP
CREATE TABLE ChiTietSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdRom UNIQUEIDENTIFIER,
IdRam UNIQUEIDENTIFIER,
IdMauSac UNIQUEIDENTIFIER,
IdCPU UNIQUEIDENTIFIER,
Gia DECIMAL(20,0) DEFAULT 0,
SoLuong int DEFAULT 0,
HinhAnh Varchar(100) DEFAULT NULL,
IdKhuyenMai UNIQUEIDENTIFIER,
IdSP UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)

GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
TenSP NVARCHAR(100) NOT NULL,
SoLuong INT NOT NULL,
Gia DECIMAL(20,0) DEFAULT 0,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (IdHoaDon,IdChiTietSP),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id),
CONSTRAINT FK2 FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id),
)
GO
--TrangThaiImel
CREATE TABLE TrangThaiImel(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) NOT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
-- Imel
CREATE TABLE Imel(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDon UNIQUEIDENTIFIER DEFAULT NULL,
IdChiTietSP UNIQUEIDENTIFIER DEFAULT NULL,
Ma INT UNIQUE NOT NULL,
IdTrangThaiImel UNIQUEIDENTIFIER,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--BaoHanh
CREATE TABLE BaoHanh(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
TrangThai Int NOT NULL,
IdImel UNIQUEIDENTIFIER,
NgayBaoHanh Date NOT NULL,
NgayHoanThanh Date DEFAULT NULL,
NgayKhachLay Date DEFAULT NULL,
CreatedDate Date DEFAULT GETDATE(),
CreateBy VARCHAR(20) NOT NULL,
lastModifiedDate Date DEFAULT NULL,
Deleted Bit DEFAULT 0
)
GO
--TẠO QUAN HỆ GIỮA CÁC BẢNG
--TaiKhoan - ChucVu
ALTER TABLE TaiKhoan ADD FOREIGN KEY (IdCV) REFERENCES ChucVu(Id)
--TaiKhoan - TrangThaiTaiKhoan
ALTER TABLE TaiKhoan ADD FOREIGN KEY (IdTrangThaiTK) REFERENCES TrangThaiTaiKhoan(Id)
-- HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
-- HoaDon - TaiKhoan
ALTER TABLE HoaDon ADD FOREIGN KEY (IdTK) REFERENCES TaiKhoan(Id)
-- HoaDon - TrangThaiHoaDon
ALTER TABLE HoaDon ADD FOREIGN KEY (IdTrangThaiHD) REFERENCES TrangThaiHoaDon(Id)
-- SanPham - Hang
ALTER TABLE SanPham ADD FOREIGN KEY (IdHang) REFERENCES Hang(Id)
-- SanPham - HDH
ALTER TABLE SanPham ADD FOREIGN KEY (IdHDH) REFERENCES HDH(Id)
-- KhuyenMai - LoaiKM
ALTER TABLE KhuyenMai ADD FOREIGN KEY (IdLoaiKM) REFERENCES LoaiKM(Id)
-- ChiTietSP - SanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSP) REFERENCES SanPham(Id)
-- ChiTietSP - ROM
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdRom) REFERENCES Rom(Id)
-- ChiTietSP - RAM
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdRam) REFERENCES Ram(Id)
-- ChiTietSP - CPU
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdCPU) REFERENCES CPU(Id)
-- ChiTietSP - MauSac
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdMauSac) REFERENCES MauSac(Id)
-- ChiTietSP - KhuyenMai
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdKhuyenMai) REFERENCES KhuyenMai(Id)
-- Imel - HoaDon
ALTER TABLE Imel ADD FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id)
-- Imel - ChiTietSP
ALTER TABLE Imel ADD FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id)
-- Imel - TrangThaiImel
ALTER TABLE Imel ADD FOREIGN KEY(IdTrangThaiImel) REFERENCES TrangThaiImel(Id)
-- BaoHanh - Imel
ALTER TABLE BaoHanh ADD FOREIGN KEY(IdImel) REFERENCES Imel(Id)
